### ISSUE TITLE
Not working in Android 7

### ISSUE THREAD

**Issue by davidkhuu** [rpmsoftware/react-native-signature-pad#14]
Issue from the original repo: kevinstumpf/react-native-signature-pad#23

I found out that the reason for this not working in Android 7 (Nougat) and higher is because Google changed the default behaviour for WebViews. In apps that use WebViews, it no longer uses the WebView APK in previous versions but instead it uses the Chrome WebView.

Source: https://developer.android.com/about/versions/nougat/android-7.0.html#webview

After disabling/uninstalling the Chrome app, signatures work again on devices that had issues. It looks like only real devices with Android 7 are affected and not simulators.

**Comment by jreason** [comment]
Still not working on Android, works fine on iOS

**Comment by davidkhuu** [comment]
@jreason do you have more information on your set-up? 
- Android version
- React Native version
- how you're using onChange or the function you're calling for onChange
- code snippet

**Comment by jreason** [comment]
@davidkhuu here is some more info
Device: Samsung SM-J530F
Android: 7.0
RN: 0.50

```
_signaturePadChange = ({base64DataUrl}) => {
        console.log("Got new signature: " + base64DataUrl);
    };

<SignaturePad onError={this._signaturePadError} onChange={this._signaturePadChange}
                              onMessage={this._onMessage} style={{flex: 1, backgroundColor: 'white'}}/>
```

Works on iOS not Android
