### ISSUE TITLE
Android not working

### ISSUE THREAD

**Issue by jreason** [rpmsoftware/react-native-signature-pad#17]
Hi,

Android is still not working.
I have tried both onChange and onMessage.

iOS is working ok!

<SignaturePad onError={this._signaturePadError} onChange={this._signaturePadChange} onMessage={this._onMessage} style={{flex: 1, backgroundColor: 'white'}}/>

**Comment by davidkhuu** [comment]
Not sure if you're still using this library.

I've merged updates/changes from the original repo so hopefully it works for you one Android now.

I'm closing this issue. If it still does not work, feel free to re-open the issue and describe your issue and environment.
